<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$archiver</key>
	<string>NSKeyedArchiver</string>
	<key>$objects</key>
	<array>
		<string>$null</string>
		<string>3755</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>32</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>3</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>31</integer>
			</dict>
			<key>X</key>
			<dict>
				<key>CF$UID</key>
				<integer>4</integer>
			</dict>
			<key>Y</key>
			<dict>
				<key>CF$UID</key>
				<integer>5</integer>
			</dict>
			<key>barcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>22</integer>
			</dict>
			<key>barxleft</key>
			<false/>
			<key>barxright</key>
			<false/>
			<key>barybottom</key>
			<false/>
			<key>barytop</key>
			<false/>
			<key>belongx</key>
			<integer>1</integer>
			<key>belongy</key>
			<integer>1</integer>
			<key>byteorder</key>
			<integer>0</integer>
			<key>color</key>
			<dict>
				<key>CF$UID</key>
				<integer>10</integer>
			</dict>
			<key>comment</key>
			<dict>
				<key>CF$UID</key>
				<integer>8</integer>
			</dict>
			<key>dash</key>
			<integer>0</integer>
			<key>dashwidth</key>
			<real>0.0</real>
			<key>dynsize</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>errorbarx</key>
			<integer>0</integer>
			<key>errorbary</key>
			<integer>0</integer>
			<key>errorcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>28</integer>
			</dict>
			<key>errorvalx</key>
			<real>0.0</real>
			<key>errorvaly</key>
			<real>0.0</real>
			<key>errorwidth</key>
			<real>1</real>
			<key>fillcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>freex</key>
			<false/>
			<key>freey</key>
			<false/>
			<key>fxmax</key>
			<real>1</real>
			<key>fxmin</key>
			<real>0.0</real>
			<key>fymax</key>
			<real>1</real>
			<key>fymin</key>
			<real>0.0</real>
			<key>havexminmax</key>
			<true/>
			<key>haveyminmax</key>
			<true/>
			<key>linewidth</key>
			<real>1</real>
			<key>plotarea</key>
			<false/>
			<key>plotdots</key>
			<false/>
			<key>plotfhist</key>
			<false/>
			<key>plothist</key>
			<false/>
			<key>plotlegend</key>
			<true/>
			<key>plotlines</key>
			<true/>
			<key>plotsymbols</key>
			<false/>
			<key>plotxbars</key>
			<false/>
			<key>plotxsticks</key>
			<false/>
			<key>plotybars</key>
			<false/>
			<key>plotysticks</key>
			<false/>
			<key>show</key>
			<true/>
			<key>source</key>
			<dict>
				<key>CF$UID</key>
				<integer>6</integer>
			</dict>
			<key>stickabs</key>
			<false/>
			<key>stickcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>sticksize</key>
			<real>20</real>
			<key>symbol</key>
			<integer>0</integer>
			<key>symbolsize</key>
			<real>10</real>
			<key>symfill</key>
			<false/>
			<key>verno</key>
			<integer>31</integer>
		</dict>
		<data>
		mpmZmZmZuT+4HoXrUbi+P+xRuB6F68E/exSuR+F6xD8K16NwPQrHP5qZmZmZ
		mck/KVyPwvUozD+4HoXrUbjOP6RwPQrXo9A/7FG4HoXr0T8zMzMzMzPTP3sU
		rkfhetQ/w/UoXI/C1T8K16NwPQrXP1K4HoXrUdg/mpmZmZmZ2T/hehSuR+Ha
		Pylcj8L1KNw/cT0K16Nw3T+4HoXrUbjePwAAAAAAAOA/pHA9Ctej4D9I4XoU
		rkfhP+xRuB6F6+E/j8L1KFyP4j8zMzMzMzPjP9ejcD0K1+M/exSuR+F65D8f
		hetRuB7lP8P1KFyPwuU/ZmZmZmZm5j8K16NwPQrnP65H4XoUruc/UrgehetR
		6D/2KFyPwvXoP5qZmZmZmek/PQrXo3A96j/hehSuR+HqP4XrUbgehes/KVyP
		wvUo7D/NzMzMzMzsP3E9CtejcO0/FK5H4XoU7j+4HoXrUbjuP1yPwvUoXO8/
		AAAAAAAA8D9SuB6F61HwP6RwPQrXo/A/9ihcj8L18D9I4XoUrkfxP5qZmZmZ
		mfE/7FG4HoXr8T89CtejcD3yP4/C9Shcj/I/4XoUrkfh8j8zMzMzMzPzP4Xr
		UbgehfM/16NwPQrX8z8pXI/C9Sj0P3sUrkfhevQ/zczMzMzM9D8fhetRuB71
		P3E9CtejcPU/w/UoXI/C9T8UrkfhehT2P2ZmZmZmZvY/uB6F61G49j8K16Nw
		PQr3P1yPwvUoXPc/rkfhehSu9z8AAAAAAAD4P1K4HoXrUfg/pHA9Ctej+D/2
		KFyPwvX4P0jhehSuR/k/mpmZmZmZ+T/sUbgehev5Pz0K16NwPfo/j8L1KFyP
		+j/hehSuR+H6PzMzMzMzM/s/hetRuB6F+z/Xo3A9Ctf7Pylcj8L1KPw/exSu
		R+F6/D/NzMzMzMz8Px+F61G4Hv0/cT0K16Nw/T/D9Shcj8L9PxSuR+F6FP4/
		ZmZmZmZm/j+4HoXrUbj+PwrXo3A9Cv8/XI/C9Shc/z+uR+F6FK7/PwAAAAAA
		AABAKVyPwvUoAEBSuB6F61EAQHsUrkfhegBApHA9CtejAEDNzMzMzMwAQPYo
		XI/C9QBAH4XrUbgeAUBI4XoUrkcBQHE9CtejcAFAmpmZmZmZAUDD9Shcj8IB
		QOxRuB6F6wFAFK5H4XoUAkA9CtejcD0CQGZmZmZmZgJAj8L1KFyPAkC4HoXr
		UbgCQOF6FK5H4QJACtejcD0KA0AzMzMzMzMDQFyPwvUoXANAhetRuB6FA0Cu
		R+F6FK4DQNejcD0K1wNAAAAAAAAABEApXI/C9SgEQFK4HoXrUQRAexSuR+F6
		BECkcD0K16MEQM3MzMzMzARA9ihcj8L1BEAfhetRuB4FQEjhehSuRwVAcT0K
		16NwBUCamZmZmZkFQMP1KFyPwgVA7FG4HoXrBUAUrkfhehQGQD0K16NwPQZA
		ZmZmZmZmBkCPwvUoXI8GQLgehetRuAZA4XoUrkfhBkAK16NwPQoHQDMzMzMz
		MwdAXI/C9ShcB0CF61G4HoUHQK5H4XoUrgdA16NwPQrXB0AAAAAAAAAIQClc
		j8L1KAhAUrgehetRCEB7FK5H4XoIQKRwPQrXowhAzczMzMzMCED2KFyPwvUI
		QB+F61G4HglASOF6FK5HCUBxPQrXo3AJQJqZmZmZmQlAw/UoXI/CCUDsUbge
		hesJQBSuR+F6FApAPQrXo3A9CkBmZmZmZmYKQI/C9ShcjwpAuB6F61G4CkDh
		ehSuR+EKQArXo3A9CgtAMzMzMzMzC0Bcj8L1KFwLQIXrUbgehQtArkfhehSu
		C0DXo3A9CtcLQAAAAAAAAAxAKVyPwvUoDEBSuB6F61EMQHsUrkfhegxApHA9
		CtejDEDNzMzMzMwMQPYoXI/C9QxAH4XrUbgeDUBI4XoUrkcNQHE9CtejcA1A
		mpmZmZmZDUDD9Shcj8INQOxRuB6F6w1AFK5H4XoUDkA9CtejcD0OQGZmZmZm
		Zg5Aj8L1KFyPDkC4HoXrUbgOQOF6FK5H4Q5ACtejcD0KD0AzMzMzMzMPQFyP
		wvUoXA9AhetRuB6FD0CuR+F6FK4PQNejcD0K1w9AAAAAAAAAEEAUrkfhehQQ
		QClcj8L1KBBAPQrXo3A9EEBSuB6F61EQQGZmZmZmZhBAexSuR+F6EECPwvUo
		XI8QQKRwPQrXoxBAuB6F61G4EEDNzMzMzMwQQOF6FK5H4RBA9ihcj8L1EEAK
		16NwPQoRQB+F61G4HhFAMzMzMzMzEUBI4XoUrkcRQFyPwvUoXBFAcT0K16Nw
		EUCF61G4HoURQJqZmZmZmRFArkfhehSuEUDD9Shcj8IRQNejcD0K1xFA7FG4
		HoXrEUAAAAAAAAASQBSuR+F6FBJAKVyPwvUoEkA9CtejcD0SQFK4HoXrURJA
		ZmZmZmZmEkB7FK5H4XoSQI/C9ShcjxJApHA9CtejEkC4HoXrUbgSQM3MzMzM
		zBJA4XoUrkfhEkD2KFyPwvUSQArXo3A9ChNAH4XrUbgeE0AzMzMzMzMTQEjh
		ehSuRxNAXI/C9ShcE0BxPQrXo3ATQIXrUbgehRNAmpmZmZmZE0CuR+F6FK4T
		QMP1KFyPwhNA16NwPQrXE0DsUbgehesTQAAAAAAAABRAFK5H4XoUFEApXI/C
		9SgUQD0K16NwPRRAUrgehetRFEBmZmZmZmYUQHsUrkfhehRAj8L1KFyPFECk
		cD0K16MUQLgehetRuBRAzczMzMzMFEDhehSuR+EUQPYoXI/C9RRACtejcD0K
		FUAfhetRuB4VQDMzMzMzMxVASOF6FK5HFUBcj8L1KFwVQHE9CtejcBVAhetR
		uB6FFUCamZmZmZkVQK5H4XoUrhVAw/UoXI/CFUDXo3A9CtcVQOxRuB6F6xVA
		AAAAAAAAFkAUrkfhehQWQClcj8L1KBZAPQrXo3A9FkBSuB6F61EWQGZmZmZm
		ZhZAexSuR+F6FkCPwvUoXI8WQKRwPQrXoxZAuB6F61G4FkDNzMzMzMwWQOF6
		FK5H4RZA9ihcj8L1FkAK16NwPQoXQB+F61G4HhdAMzMzMzMzF0BI4XoUrkcX
		QFyPwvUoXBdAcT0K16NwF0CF61G4HoUXQJqZmZmZmRdArkfhehSuF0DD9Shc
		j8IXQNejcD0K1xdA7FG4HoXrF0AAAAAAAAAYQBSuR+F6FBhAKVyPwvUoGEA9
		CtejcD0YQFK4HoXrURhAZmZmZmZmGEB7FK5H4XoYQI/C9ShcjxhApHA9Ctej
		GEC4HoXrUbgYQM3MzMzMzBhA4XoUrkfhGED2KFyPwvUYQArXo3A9ChlAH4Xr
		UbgeGUAzMzMzMzMZQEjhehSuRxlAXI/C9ShcGUBxPQrXo3AZQIXrUbgehRlA
		mpmZmZmZGUCuR+F6FK4ZQMP1KFyPwhlA16NwPQrXGUDsUbgehesZQAAAAAAA
		ABpAFK5H4XoUGkApXI/C9SgaQD0K16NwPRpAUrgehetRGkBmZmZmZmYaQHsU
		rkfhehpAj8L1KFyPGkCkcD0K16MaQLgehetRuBpAzczMzMzMGkDhehSuR+Ea
		QPYoXI/C9RpACtejcD0KG0AfhetRuB4bQDMzMzMzMxtASOF6FK5HG0Bcj8L1
		KFwbQHE9CtejcBtAhetRuB6FG0CamZmZmZkbQK5H4XoUrhtAw/UoXI/CG0DX
		o3A9CtcbQOxRuB6F6xtAAAAAAAAAHEAUrkfhehQcQClcj8L1KBxAPQrXo3A9
		HEBSuB6F61EcQGZmZmZmZhxAexSuR+F6HECPwvUoXI8cQKRwPQrXoxxAuB6F
		61G4HEDNzMzMzMwcQOF6FK5H4RxA9ihcj8L1HEAK16NwPQodQB+F61G4Hh1A
		MzMzMzMzHUBI4XoUrkcdQFyPwvUoXB1AcT0K16NwHUCF61G4HoUdQJqZmZmZ
		mR1ArkfhehSuHUDD9Shcj8IdQNejcD0K1x1A7FG4HoXrHUAAAAAAAAAeQBSu
		R+F6FB5AKVyPwvUoHkA9CtejcD0eQFK4HoXrUR5AZmZmZmZmHkB7FK5H4Xoe
		QI/C9Shcjx5ApHA9CtejHkC4HoXrUbgeQM3MzMzMzB5A4XoUrkfhHkD2KFyP
		wvUeQArXo3A9Ch9AH4XrUbgeH0AzMzMzMzMfQEjhehSuRx9AXI/C9ShcH0Bx
		PQrXo3AfQIXrUbgehR9AmpmZmZmZH0CuR+F6FK4fQMP1KFyPwh9A16NwPQrX
		H0DsUbgehesfQAAAAAAAACBACtejcD0KIEAUrkfhehQgQB+F61G4HiBAKVyP
		wvUoIEAzMzMzMzMgQD0K16NwPSBASOF6FK5HIEBSuB6F61EgQFyPwvUoXCBA
		ZmZmZmZmIEBxPQrXo3AgQHsUrkfheiBAhetRuB6FIECPwvUoXI8gQJqZmZmZ
		mSBApHA9CtejIECuR+F6FK4gQLgehetRuCBAw/UoXI/CIEDNzMzMzMwgQNej
		cD0K1yBA4XoUrkfhIEDsUbgehesgQPYoXI/C9SBAAAAAAAAAIUAK16NwPQoh
		QBSuR+F6FCFAH4XrUbgeIUApXI/C9SghQDMzMzMzMyFAPQrXo3A9IUBI4XoU
		rkchQFK4HoXrUSFAXI/C9ShcIUBmZmZmZmYhQHE9CtejcCFAexSuR+F6IUCF
		61G4HoUhQI/C9ShcjyFAmpmZmZmZIUCkcD0K16MhQK5H4XoUriFAuB6F61G4
		IUDD9Shcj8IhQM3MzMzMzCFA16NwPQrXIUDhehSuR+EhQOxRuB6F6yFA9ihc
		j8L1IUAAAAAAAAAiQArXo3A9CiJAFK5H4XoUIkAfhetRuB4iQClcj8L1KCJA
		MzMzMzMzIkA9CtejcD0iQEjhehSuRyJAUrgehetRIkBcj8L1KFwiQGZmZmZm
		ZiJAcT0K16NwIkB7FK5H4XoiQIXrUbgehSJAj8L1KFyPIkCamZmZmZkiQKRw
		PQrXoyJArkfhehSuIkC4HoXrUbgiQMP1KFyPwiJAzczMzMzMIkDXo3A9Ctci
		QOF6FK5H4SJA7FG4HoXrIkD2KFyPwvUiQAAAAAAAACNACtejcD0KI0AUrkfh
		ehQjQB+F61G4HiNAKVyPwvUoI0AzMzMzMzMjQD0K16NwPSNASOF6FK5HI0BS
		uB6F61EjQFyPwvUoXCNAZmZmZmZmI0BxPQrXo3AjQHsUrkfheiNAhetRuB6F
		I0CPwvUoXI8jQJqZmZmZmSNApHA9CtejI0CuR+F6FK4jQLgehetRuCNAw/Uo
		XI/CI0DNzMzMzMwjQNejcD0K1yNA4XoUrkfhI0DsUbgehesjQPYoXI/C9SNA
		AAAAAAAAJEA=
		</data>
		<data>
		u7iNBvAW8j8aqIx/n3HfP03zjlN0JOw/EoPAyqFF8D/67evAOSPwP3UCmggb
		nvQ/64uEtpxL6D+5NlSM8zfvP6UsQxzr4vA/jnVxGw3g8z8U7Sqk/KTuP5zE
		ILByaPU/CRueXinL9D/HSzeJQWDsPxrdQexMoeo/EJIFTODW7j8SFD/G3LX4
		PxB6Nqs+V/E/bxKDwMqh9j99eQH20anoP7IubqMBvPY/ZohjXdxG+z8tQxzr
		4jb5P/YLdsO2Re4/TKYKRiV18T9iodY07zj1PyuHFtnO9/M/PQrXo3A98T/B
		qKROQBP7P0vIBz2bVfw/C7Wmeccp+j+6SQwCK4f3P1Frmnecovw/VFInoImw
		8j++wRcmUwX5P2/whclUwf0/b4EExY8x/D/5D+m3rwPyP7MMcayL2/Q/YTJV
		MCqp9D8hsHJoke30PyL99nXgnPc/hiAHJcy07D/ImLuWkA/3P34YITzaOOo/
		9Ik8Sbpm7T/8qfHSTWLzPxh47j1ccuw/UwWjkjoB+j9WDi2yne/4P7mNBvAW
		SPE/xm00gLdA9T8IPZtVn6v1P6qCUUmdgPU/QWX8+4wL5j9FEr2MYrnvPzSA
		t0CC4vc/m+Ydp+hI8D/B/1ayYyPrPyxlGeJYF/Y/+MJkqmBU8z9CPujZrPr0
		PxB6Nqs+V9s/EoPAyqFF8T9MpgpGJXXxP3zysFBrmvM/jLlrCfmg8T8Plxx3
		SgfhPx3J5T+k3/A/bagY529C7j8qOpLLf0jxP/5D+u3rwNM/xHx5AfbR6j/Q
		7SWN0TrQPwTKplzhXeE/Zyyazk4Gwz/76NSVz/LiP+G04EVfQco/ieqtga0S
		zD/f+NozSwLmP6yowTQMH+k/B3x+GCE80D/WWMLaGDu1v6VJKej2kr6/dZMY
		BFYO5j+TVRFuMqq0P23/ykqTUuA/yv0ORYE+1z+jAbwFEhTLv21zY3rCEsO/
		WrvtQnOdvr/3OxQF+kTSvwHeAgmKH8s/66urArUYtD9dwwyNJ4KYP2qHvyZr
		1MM/nu+nxks3yb80gLdAguLgv/+VlSaloMe/mQzH8xlQn7+CqPsApDbXv5cc
		d0oH6+C/uk/pu7YSZT+W7UPecvWjP+s56X3ja8e/EJIFTODWvb8z3IDPDyPS
		P1bxRuaRP9S/91j60AX1279SRIZVvJHdvzmX4qqy7+K/nIpUGFsI1L9KQbeX
		NEazPw2LUdfa+7i/dk8eFmpN179s7BLVWwPhvwxcHmtGBok/LLzLRXwnvr9z
		hXe5iO/Evw3gLZCg+Nu/RuuoaoKo1b8W9INfjy57vwqi7gOQ2qy/9wFIbeLk
		vr8K16NwPQrfvwUVVb/S+ai/eH+8V61MxD93+GuyRj3YP7NeDOVEu7q/zemy
		mNh81D/Jq3MMyF7bP1lpUgq6vdC/lnfVA+Yhk78a+ie4WFHZv4oCfSJPkp6/
		3/jaM0sC1j9TIoleRrHaP2k6OxkcJdk/6IcRwqONz7875Ga4AZ/kP8Cy0qQU
		dMM/Z9Xnaiv25D8H6/8c5svTP+QPBp57D+E/DVTGv8+42j8TYcPTK2XdP4o8
		Sbpm8uk/RG6GG/D5zT+Lw5lfzQHgPz0s1JrmHdk/U7MHWoEh0T8dVU0QdR/S
		P8YWghyUMOs/iXssfeiC6j//7EeKyLDnP9lCkIMSZu8/InGPpQ9d7j9OC170
		FaTRP5YhjnVxG/I/M8SxLm6j7T8TJ/c7FAXuP0QX1LfM6d4//Yf029eB4j/d
		6jnpfePpPyRFZFjFG9U/4syv5gDB4j8QdR+A1CbmP9RgGoaPiOg/jq89syRA
		2T+PGaiMf5/kPzC7Jw8Lteo/Oq+xS1Rv6z+V1AloImzzP7iSHRuBeOc/iPTb
		14Fz9D8noImw4en2PytNSkG3l+M/8WPMXUvI8j8NcayL22juP/Dce7jkuO4/
		X5hMFYxK6z/IBz2bVZ/yP3h6pSxDHPI/T0ATYcPT8T9KtU/HYwbvP8fXnlkS
		oO0/vp8aL90k9z9ZF7fRAN73P8nlP6Tfvug/qoJRSZ2A8T882jhiLT7sP7By
		aJHtfO4/AU2EDU+v9j89D+7O2m3qP+cAwRw9fuE/qoJRSZ2A8j/DtkWZDTLs
		P/p+arx0k/Y/dQKaCBue9T97vfvjvWrpP1vTvOMUHfU/30+Nl24S8j9nRGlv
		8IX0PwgDz72HS94/YLAbti3K5j9uNIC3QIL1PyCYo8fvbeM/NnaJ6q2B6D8H
		zhlR2hvwPz0nvW987eM/mZ6wxAPK4T8VOq+xS1TrPygPC7WmefE/EmvxKQDG
		4j99kdCWcynjP3PXEvJBz/E/mQ0yychZ6z93EDtT6LzaP3Tqymd5Hu8/mfBL
		/byp7z9GJXUCmgjwP4tUGFsIcuE/yEEJM23/2D9M/bypSIXfP/FL/bypSOE/
		ZY16iEZ37D94RfC/ley4P447pYP1f8I/MIFbd/NU3T9MbD6uDRXgP3P0+L1N
		f+w/Mo/8wcBz1z8YCW05l+LeP1D8GHPXEuE/M+GX+nlTyT+eeM4WEFqfv+cd
		p+hILuQ/nE8dq5SeoT+nP/uRIjLeP23i5H6Hori/QRAgQ8cOmr9yFva0w1/g
		P4R+pl63CLC/aVIKur2k2z8fSx+6oL7gP2R1q+ek99k/s++K4H8r2T+78lme
		B3fhP2zQl97+XLA/DYl7LH3o0L9VwaikTkDlP0dWfhmMEbk/HNDSFWwjtj/o
		3sMlx53Gv+SDns2qz80/s0EmGTkL1T/ir8ka9RC9P5ayDHGsi8s/MgOV8e8z
		2j8AdJgvL8CuP/4ORYE+kdU/XynLEMe6wD9fe2ZJgJrgP3AIVWr2QOM/3X2O
		jxZnsD+ztb5IaMvBPw/wpIXLKqy/oOBiRQ2m2T+NnIU97fDLvy7nUlxV9tc/
		4ZnQJLGkrD9qwYu+gjTZv6t5jsh3Kbm/v0NRoE/k2T/OUx1yM9zaPwn+t5Id
		G6E/F/GdmPVi4D9O0ZFc/kPGv7we8dAc/n+/DB8RUyKJvj8YCW05l+KqvyKm
		RBK9jNo/3PRnP1JEzj9dAHVevlB7v8zxCkRPyqS/b57qkJvh3D9oWmJlNPKZ
		vzSFzmvsEtM/kpGzsKcdvj9v2LYos0HQv5xTyQBQxZ2/je4gdqbQ3T/luFM6
		WP/dP7ZnlgSoqcU/KuPfZ1w43D8GY0Si0LKyv+p7DcFxGZe/dXYyOEpe2T9F
		gT6RJ0nRPxWRYRVvZOU/RnwnZr0Y5z8K9Ik8SbrlP9/42jNLAtA/+THmriXk
		5z/+SBEZVvHUP5jArbt5quw/2T15WKg10z/uQnOdRlrGP73jFB3J5eE/vfvj
		vWpluj+mJyzxgLLmP8o329yYnuw/Pj+MEB5tyD++pDFaR1XjP+XQItv5fuM/
		p1zhXS7i4T9kO99PjZfqP9l8XBsqxtU/Pq4NFeP80T+8lpAPejbrP4Emwoan
		V/E/JzEIrBxa5j9txf6ye/LxP2dhTzv8NeI/XaeRlsrb4T/de7jkuFPYP9u/
		stKkFNA/MsnIWdjT2j/jpZvEILDsP4JzRpT2BvM/onprYKsE7T/r4jYawFvn
		Pz+RJ0nXTOk/HCWvzjEg1z/Q1VbsL7vwP7bz/dR46fA/0m9fB84Z8j+WQ4ts
		5/vyPz+MEB5tHOg/pPyk2qfj7z9kWMUbmUfcP+l942vPLN0/E/JBz2bV8j83
		iUFg5dDzP/ZiKCfaVeU/NzemJyzx7j+05VyKq8rnPx/0bFZ9rvA/ETY8vVKW
		8z9F9dbAVgnnP9Xnaiv2l+M/KnReY5eo6z956SYxCKzuPwzqW+Z0Wew/Nuoh
		Gt1B6z+WQ4ts5/vyP6w5QDBHj+U/PE7RkVz+8z/m6PF7m/7vPz81XrpJDPM/
		CRueXinL8z/USEvl7QjiP9YcIJijx+I/v5oDBHP07T97MZQT7SrUPyhhpu1f
		WeE/RUdy+Q/p8D+vWpnwS/3hPxCv6xfshu8/5dAi2/l+8j8kRWRYxRvpP1JJ
		nYAmwuk/eNFXkGYs7j9xcr9DUaDmPxoXDoRkAec/W7G/7J487T80LhwIyQLg
		P2kdVU0Qddk/Pbg7a7ddxD94YtaLoZzaP7pJDAIrh/A/YB+duvJZ3D+kwthC
		kIPCPxwlr84xINE/l+Kqsu+K6z+mft5UpMKoP4CCixU1mO8/ZOlDF9S34D92
		bATidf3hPyfeAZ60cKk/OGbZk8DmjL/LLa2GxD3WPwkzbf/KSuc/VB1yM9yA
		4j+V8e8zLhzsP5g0Ruuoato/UN8yp8tiyj9+Uu3T8ZjJP7RZ9bnaiuE/8KfG
		SzeJ4z8ouFhRg2njP0Mc6+I2Gto/zczMzMzM5D+5quy7IvjTP3tmSYCaWug/
		eO+oMSHmqr88iJ0pdF7ZPww89x4uOb6/Wg2Jeyx9zD8LDFnd6jnJP15ortNI
		S8W/qmBUUiegwb/a/pWVJqXWP6Zh+IiYEsU/OZfiqrLvuj/v4ZLjTungPwHB
		HD1+b8M/18BWCRaHoz/Jk6RrJt/cPyjS/ZyC/LS/CFVq9kAr3j9xcr9DUaDR
		P4p2FVJ+Utk/HlA25Qrv3j8nJrkNtExwv0X11sBWCdA/wt1Zu+1C5T8bZJKR
		s7DbPzWZ8bbSa6s/5US7Cik/3z/NdRppqbzNP38SnzvB/qO/NBE2PL1S3D+8
		XMR3YtbLvwnh0cYRa98/c0urIXGPrT8JG55eKcvWPxIxJZLoZcS/KQXdXtIY
		ub9pqbwd4bTUP1cm/FI/b+g/VrAyvz9KUb/RrkLKT6rBPzJVMCqpE+o/h1Cl
		Zg+0yj8q/u+ICtWxv7NBJhk5C8s/Ad4CCYof2T91HaopyTq4PwkWhzO/muA/
		gnNGlPYG5T/ImLuWkA+iP00xB0FHq5o/vi8uVWmLsz9I3GPpQxfgP97IPPIH
		A+U/7l9ZaVIK4T+daFch5SeVPyGwcmiR7cA/w0fElEiixz8uknajj/mgvyR/
		MPDce8g/w552+Guyxj9Yc4Bgjh7bP4PAyqFFttE/W18ktOVc6D9Z3eo56X3k
		P+8gdqbQebU/wELmyqDatD/r4jYawFvrP9NqSNxj6ec/rvAuF/Gd7T8oCvSJ
		PEnSP6d5xyk6kuY/7Bfshm2L2j+cUIiAQ6jrP0D7kSIyrOM/MdP2r6w06D84
		Z0Rpb/DuP1uZ8Ev9vMU/zTtO0ZFc4T/nNXaJ6q3jPwisHFpkO/E/7uvAOSNK
		7z9c5nRZTGzgPzcawFsgQe8/WOIBZVOu6T8L0oxF09noP6mHaHQHsds/l/+Q
		fvs68T/EfHkB9tHpP83MzMzMzNI/CMkCJnDr7z+YF2AfnbrUPzBkdavnpMc/
		XdxGA3gL8j8=
		</data>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string>/Users/laovorak/Desktop/illustrator class 270416/Workshop2/data.txt</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableString</string>
				<string>NSString</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableString</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string>Import</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>11</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>14</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>NSColor pasteboard type</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableSet</string>
				<string>NSSet</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableSet</string>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MAA=
			</data>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSColor</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSColor</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSColorWell</string>
				<string>NSControl</string>
				<string>NSView</string>
				<string>NSResponder</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSColorWell</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>21</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>20</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MC42NjY2NjY2NjY3AA==
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>23</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>24</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>26</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>27</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>29</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>30</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>DataBuffer</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>DataBuffer</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableArray</string>
				<string>NSArray</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableArray</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>32</integer>
			</dict>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>32</integer>
			</dict>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>36</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>37</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>41</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>39</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>40</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MQA=
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>41</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>43</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>44</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<string>Helvetica</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSFont</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSFont</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>49</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>50</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>41</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>52</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>53</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>56</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>57</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>64</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>65</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>67</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MC4zMzMzMzMzMzMzAA==
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>71</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>72</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>74</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>75</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>77</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>78</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>84</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableDictionary</string>
				<string>NSDictionary</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableDictionary</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>87</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>88</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>95</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>96</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>98</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>99</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>101</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>102</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>104</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>105</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>107</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>108</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>84</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>116</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>117</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>124</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>125</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>127</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>128</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>130</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>131</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>133</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>134</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>136</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>137</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>84</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>145</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>146</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>153</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>154</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>156</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>157</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>159</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>160</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>162</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>163</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>165</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>166</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>84</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
	</array>
	<key>$top</key>
	<dict>
		<key>alabel0</key>
		<dict>
			<key>CF$UID</key>
			<integer>83</integer>
		</dict>
		<key>alabel1</key>
		<dict>
			<key>CF$UID</key>
			<integer>113</integer>
		</dict>
		<key>alabel2</key>
		<dict>
			<key>CF$UID</key>
			<integer>142</integer>
		</dict>
		<key>alabel3</key>
		<dict>
			<key>CF$UID</key>
			<integer>171</integer>
		</dict>
		<key>align0</key>
		<integer>2</integer>
		<key>align1</key>
		<integer>4</integer>
		<key>align2</key>
		<integer>6</integer>
		<key>align3</key>
		<integer>8</integer>
		<key>alldraw</key>
		<false/>
		<key>angle0</key>
		<real>0.0</real>
		<key>angle1</key>
		<real>0.0</real>
		<key>angle2</key>
		<real>0.0</real>
		<key>angle3</key>
		<real>0.0</real>
		<key>arrowsize</key>
		<real>10</real>
		<key>arrowtype</key>
		<integer>0</integer>
		<key>axis0</key>
		<true/>
		<key>axis1</key>
		<true/>
		<key>axis2</key>
		<false/>
		<key>axis3</key>
		<false/>
		<key>axismode0</key>
		<integer>0</integer>
		<key>axismode1</key>
		<integer>0</integer>
		<key>axismode2</key>
		<integer>0</integer>
		<key>axismode3</key>
		<integer>0</integer>
		<key>axistext0</key>
		<dict>
			<key>CF$UID</key>
			<integer>54</integer>
		</dict>
		<key>axistext1</key>
		<dict>
			<key>CF$UID</key>
			<integer>85</integer>
		</dict>
		<key>axistext2</key>
		<dict>
			<key>CF$UID</key>
			<integer>114</integer>
		</dict>
		<key>axistext3</key>
		<dict>
			<key>CF$UID</key>
			<integer>143</integer>
		</dict>
		<key>axistextcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>55</integer>
		</dict>
		<key>axistextcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>86</integer>
		</dict>
		<key>axistextcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>115</integer>
		</dict>
		<key>axistextcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>144</integer>
		</dict>
		<key>axistimeformat0</key>
		<dict>
			<key>CF$UID</key>
			<integer>58</integer>
		</dict>
		<key>axistimeformat1</key>
		<dict>
			<key>CF$UID</key>
			<integer>89</integer>
		</dict>
		<key>axistimeformat2</key>
		<dict>
			<key>CF$UID</key>
			<integer>118</integer>
		</dict>
		<key>axistimeformat3</key>
		<dict>
			<key>CF$UID</key>
			<integer>147</integer>
		</dict>
		<key>backgroundcolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>38</integer>
		</dict>
		<key>buffer</key>
		<dict>
			<key>CF$UID</key>
			<integer>2</integer>
		</dict>
		<key>crossarrows</key>
		<integer>0</integer>
		<key>dp0</key>
		<integer>2</integer>
		<key>dp1</key>
		<integer>2</integer>
		<key>dp2</key>
		<integer>2</integer>
		<key>dp3</key>
		<integer>2</integer>
		<key>dpauto0</key>
		<true/>
		<key>dpauto1</key>
		<true/>
		<key>dpauto2</key>
		<true/>
		<key>dpauto3</key>
		<true/>
		<key>drawbackground</key>
		<true/>
		<key>drawframe</key>
		<true/>
		<key>drawmargin</key>
		<true/>
		<key>expoff0</key>
		<integer>5</integer>
		<key>expoff1</key>
		<integer>5</integer>
		<key>expoff2</key>
		<integer>5</integer>
		<key>expoff3</key>
		<integer>5</integer>
		<key>fliptext0</key>
		<false/>
		<key>fliptext1</key>
		<false/>
		<key>fliptext2</key>
		<false/>
		<key>fliptext3</key>
		<false/>
		<key>forceframe</key>
		<false/>
		<key>forcerenderhigh</key>
		<false/>
		<key>framearrows</key>
		<false/>
		<key>framecolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>35</integer>
		</dict>
		<key>framestyle</key>
		<integer>0</integer>
		<key>framewidth</key>
		<real>2</real>
		<key>graphic</key>
		<dict>
			<key>CF$UID</key>
			<integer>34</integer>
		</dict>
		<key>grid0</key>
		<false/>
		<key>grid1</key>
		<false/>
		<key>grid2</key>
		<false/>
		<key>grid3</key>
		<false/>
		<key>gridcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>66</integer>
		</dict>
		<key>gridcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>97</integer>
		</dict>
		<key>gridcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>126</integer>
		</dict>
		<key>gridcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>155</integer>
		</dict>
		<key>gridfront0</key>
		<true/>
		<key>gridfront1</key>
		<true/>
		<key>gridfront2</key>
		<true/>
		<key>gridfront3</key>
		<true/>
		<key>gridpattern0</key>
		<integer>0</integer>
		<key>gridpattern1</key>
		<integer>0</integer>
		<key>gridpattern2</key>
		<integer>0</integer>
		<key>gridpattern3</key>
		<integer>0</integer>
		<key>gridwidth0</key>
		<real>0.5</real>
		<key>gridwidth1</key>
		<real>0.5</real>
		<key>gridwidth2</key>
		<real>0.5</real>
		<key>gridwidth3</key>
		<real>0.5</real>
		<key>legendbg</key>
		<false/>
		<key>legendbgcolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>51</integer>
		</dict>
		<key>legendcolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>48</integer>
		</dict>
		<key>legendfont</key>
		<dict>
			<key>CF$UID</key>
			<integer>45</integer>
		</dict>
		<key>legendhorizontal</key>
		<false/>
		<key>legendspace</key>
		<integer>20</integer>
		<key>legendwidth</key>
		<integer>80</integer>
		<key>legendx</key>
		<integer>100</integer>
		<key>legendy</key>
		<integer>257</integer>
		<key>marginbottom</key>
		<real>80</real>
		<key>margincolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>42</integer>
		</dict>
		<key>marginleft</key>
		<real>80</real>
		<key>marginright</key>
		<real>10</real>
		<key>margintop</key>
		<real>10</real>
		<key>mgrid0</key>
		<false/>
		<key>mgrid1</key>
		<false/>
		<key>mgrid2</key>
		<false/>
		<key>mgrid3</key>
		<false/>
		<key>mgridcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>73</integer>
		</dict>
		<key>mgridcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>103</integer>
		</dict>
		<key>mgridcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>132</integer>
		</dict>
		<key>mgridcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>161</integer>
		</dict>
		<key>mgridfront0</key>
		<true/>
		<key>mgridfront1</key>
		<true/>
		<key>mgridfront2</key>
		<true/>
		<key>mgridfront3</key>
		<true/>
		<key>mgridpattern0</key>
		<integer>0</integer>
		<key>mgridpattern1</key>
		<integer>0</integer>
		<key>mgridpattern2</key>
		<integer>0</integer>
		<key>mgridpattern3</key>
		<integer>0</integer>
		<key>mgridwidth0</key>
		<real>0.5</real>
		<key>mgridwidth1</key>
		<real>0.5</real>
		<key>mgridwidth2</key>
		<real>0.5</real>
		<key>mgridwidth3</key>
		<real>0.5</real>
		<key>mtickcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>70</integer>
		</dict>
		<key>mtickcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>100</integer>
		</dict>
		<key>mtickcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>129</integer>
		</dict>
		<key>mtickcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>158</integer>
		</dict>
		<key>mticklength0</key>
		<real>5</real>
		<key>mticklength1</key>
		<real>5</real>
		<key>mticklength2</key>
		<real>5</real>
		<key>mticklength3</key>
		<real>5</real>
		<key>mticks0</key>
		<true/>
		<key>mticks1</key>
		<true/>
		<key>mticks2</key>
		<true/>
		<key>mticks3</key>
		<true/>
		<key>mticksboth0</key>
		<false/>
		<key>mticksboth1</key>
		<false/>
		<key>mticksboth2</key>
		<false/>
		<key>mticksboth3</key>
		<false/>
		<key>mtickwidth0</key>
		<real>1</real>
		<key>mtickwidth1</key>
		<real>1</real>
		<key>mtickwidth2</key>
		<real>1</real>
		<key>mtickwidth3</key>
		<real>1</real>
		<key>numbers0</key>
		<true/>
		<key>numbers1</key>
		<true/>
		<key>numbers2</key>
		<true/>
		<key>numbers3</key>
		<true/>
		<key>numfont0</key>
		<dict>
			<key>CF$UID</key>
			<integer>62</integer>
		</dict>
		<key>numfont1</key>
		<dict>
			<key>CF$UID</key>
			<integer>93</integer>
		</dict>
		<key>numfont2</key>
		<dict>
			<key>CF$UID</key>
			<integer>122</integer>
		</dict>
		<key>numfont3</key>
		<dict>
			<key>CF$UID</key>
			<integer>151</integer>
		</dict>
		<key>numoff0</key>
		<integer>5</integer>
		<key>numoff1</key>
		<integer>5</integer>
		<key>numoff2</key>
		<integer>5</integer>
		<key>numoff3</key>
		<integer>5</integer>
		<key>plotlegend</key>
		<false/>
		<key>plotversion</key>
		<dict>
			<key>CF$UID</key>
			<integer>1</integer>
		</dict>
		<key>reverse0</key>
		<false/>
		<key>reverse1</key>
		<false/>
		<key>reverse2</key>
		<false/>
		<key>reverse3</key>
		<false/>
		<key>scaleexpr0</key>
		<dict>
			<key>CF$UID</key>
			<integer>59</integer>
		</dict>
		<key>scaleexpr1</key>
		<dict>
			<key>CF$UID</key>
			<integer>90</integer>
		</dict>
		<key>scaleexpr2</key>
		<dict>
			<key>CF$UID</key>
			<integer>119</integer>
		</dict>
		<key>scaleexpr3</key>
		<dict>
			<key>CF$UID</key>
			<integer>148</integer>
		</dict>
		<key>scalend0</key>
		<dict>
			<key>CF$UID</key>
			<integer>80</integer>
		</dict>
		<key>scalend1</key>
		<dict>
			<key>CF$UID</key>
			<integer>110</integer>
		</dict>
		<key>scalend2</key>
		<dict>
			<key>CF$UID</key>
			<integer>139</integer>
		</dict>
		<key>scalend3</key>
		<dict>
			<key>CF$UID</key>
			<integer>168</integer>
		</dict>
		<key>scalminticks0</key>
		<dict>
			<key>CF$UID</key>
			<integer>82</integer>
		</dict>
		<key>scalminticks1</key>
		<dict>
			<key>CF$UID</key>
			<integer>112</integer>
		</dict>
		<key>scalminticks2</key>
		<dict>
			<key>CF$UID</key>
			<integer>141</integer>
		</dict>
		<key>scalminticks3</key>
		<dict>
			<key>CF$UID</key>
			<integer>170</integer>
		</dict>
		<key>scalspace0</key>
		<dict>
			<key>CF$UID</key>
			<integer>81</integer>
		</dict>
		<key>scalspace1</key>
		<dict>
			<key>CF$UID</key>
			<integer>111</integer>
		</dict>
		<key>scalspace2</key>
		<dict>
			<key>CF$UID</key>
			<integer>140</integer>
		</dict>
		<key>scalspace3</key>
		<dict>
			<key>CF$UID</key>
			<integer>169</integer>
		</dict>
		<key>scalstart0</key>
		<dict>
			<key>CF$UID</key>
			<integer>79</integer>
		</dict>
		<key>scalstart1</key>
		<dict>
			<key>CF$UID</key>
			<integer>109</integer>
		</dict>
		<key>scalstart2</key>
		<dict>
			<key>CF$UID</key>
			<integer>138</integer>
		</dict>
		<key>scalstart3</key>
		<dict>
			<key>CF$UID</key>
			<integer>167</integer>
		</dict>
		<key>smalllog0</key>
		<false/>
		<key>smalllog1</key>
		<false/>
		<key>smalllog2</key>
		<false/>
		<key>smalllog3</key>
		<false/>
		<key>subviews</key>
		<integer>0</integer>
		<key>text</key>
		<dict>
			<key>CF$UID</key>
			<integer>33</integer>
		</dict>
		<key>text0</key>
		<true/>
		<key>text1</key>
		<true/>
		<key>text2</key>
		<true/>
		<key>text3</key>
		<true/>
		<key>textfont0</key>
		<dict>
			<key>CF$UID</key>
			<integer>61</integer>
		</dict>
		<key>textfont1</key>
		<dict>
			<key>CF$UID</key>
			<integer>92</integer>
		</dict>
		<key>textfont2</key>
		<dict>
			<key>CF$UID</key>
			<integer>121</integer>
		</dict>
		<key>textfont3</key>
		<dict>
			<key>CF$UID</key>
			<integer>150</integer>
		</dict>
		<key>textoff0</key>
		<integer>5</integer>
		<key>textoff1</key>
		<integer>5</integer>
		<key>textoff2</key>
		<integer>5</integer>
		<key>textoff3</key>
		<integer>5</integer>
		<key>textoffsetfromframe0</key>
		<false/>
		<key>textoffsetfromframe1</key>
		<false/>
		<key>textoffsetfromframe2</key>
		<false/>
		<key>textoffsetfromframe3</key>
		<false/>
		<key>tickcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>63</integer>
		</dict>
		<key>tickcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>94</integer>
		</dict>
		<key>tickcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>123</integer>
		</dict>
		<key>tickcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>152</integer>
		</dict>
		<key>ticklength0</key>
		<real>10</real>
		<key>ticklength1</key>
		<real>10</real>
		<key>ticklength2</key>
		<real>10</real>
		<key>ticklength3</key>
		<real>10</real>
		<key>ticks0</key>
		<true/>
		<key>ticks1</key>
		<true/>
		<key>ticks2</key>
		<true/>
		<key>ticks3</key>
		<true/>
		<key>ticksboth0</key>
		<false/>
		<key>ticksboth1</key>
		<false/>
		<key>ticksboth2</key>
		<false/>
		<key>ticksboth3</key>
		<false/>
		<key>tickstyle0</key>
		<integer>0</integer>
		<key>tickstyle1</key>
		<integer>0</integer>
		<key>tickstyle2</key>
		<integer>0</integer>
		<key>tickstyle3</key>
		<integer>0</integer>
		<key>tickwidth0</key>
		<real>2</real>
		<key>tickwidth1</key>
		<real>2</real>
		<key>tickwidth2</key>
		<real>2</real>
		<key>tickwidth3</key>
		<real>2</real>
		<key>trigger0</key>
		<dict>
			<key>CF$UID</key>
			<integer>60</integer>
		</dict>
		<key>trigger1</key>
		<dict>
			<key>CF$UID</key>
			<integer>91</integer>
		</dict>
		<key>trigger2</key>
		<dict>
			<key>CF$UID</key>
			<integer>120</integer>
		</dict>
		<key>trigger3</key>
		<dict>
			<key>CF$UID</key>
			<integer>149</integer>
		</dict>
		<key>verno</key>
		<integer>31</integer>
		<key>winh</key>
		<integer>410</integer>
		<key>winw</key>
		<integer>762</integer>
		<key>winx</key>
		<integer>287</integer>
		<key>winy</key>
		<integer>256</integer>
		<key>xmax1</key>
		<real>10.565714285714286</real>
		<key>xmax2</key>
		<real>1</real>
		<key>xmin1</key>
		<real>-0.46571428571428575</real>
		<key>xmin2</key>
		<real>0.0</real>
		<key>ymax1</key>
		<real>2.1085791878172588</real>
		<key>ymax2</key>
		<real>1</real>
		<key>ymin1</key>
		<real>-0.84063918781725888</real>
		<key>ymin2</key>
		<real>0.0</real>
		<key>zerocolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>76</integer>
		</dict>
		<key>zerocolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>106</integer>
		</dict>
		<key>zerocolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>135</integer>
		</dict>
		<key>zerocolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>164</integer>
		</dict>
		<key>zeroline0</key>
		<false/>
		<key>zeroline1</key>
		<false/>
		<key>zeroline2</key>
		<false/>
		<key>zeroline3</key>
		<false/>
	</dict>
	<key>$version</key>
	<integer>100000</integer>
</dict>
</plist>
